
version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 172.20.0.2
        
  goapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      app_net:
        ipv4_address: 172.20.0.3

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
volumes:
  postgres_data:

